---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  namespace: beekeeper
  name: beekeeper-ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: beekeeper-tls
    hosts:
    - beekeeper-tls
  rules:
  - host: beekeeper.hack.gt
    http:
      paths:
      - backend:
          serviceName: beekeeper-default
          servicePort: 80
 