---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  namespace: beekeeper
  name: beekeeper-ingress
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: beekeeper-tls
    hosts:
    - beekeeper.hack.gt
  rules:
  - host: beekeeper.hack.gt
    http:
      paths:
      - backend:
          serviceName: beekeeper-default
          servicePort: 80
 