---
apiVersion: v1
kind: Service
metadata:
  namespace: beekeeper
  labels:
    name: beekeeper-default
    heritage: Biodomes
  name: beekeeper-default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    name: beekeeper-default
